#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

#PATH = '/etc/userbot/'
PATH = os.getcwd()
os.chdir(PATH)

from sysb.daemon import *


def main():
    if len(sys.argv) == 1:
        sys.argv.append('')

    if sys.argv[1] in ('--stop', '--restart'):
        startstop(stdout=os.getcwd()+'/userbot.log', pidfile='/tmp/userbot.pid')
        if sys.argv[1] == '--restart':
            sys.argv[1] = '--start'

    if sys.argv[1] == '--start':
        if not '--no-daemon' in sys.argv:
            import logging
            args = {'format': '%(asctime)s:%(levelname)s:%(name)s: %(message)s'}
            func = logging.basicConfig
        else:
            import coloredlogs
            args = {}
            func = coloredlogs.install

        if '--debug=1' in sys.argv:
            args['level'] = 10
            func(**args)

        elif '--debug=2' in sys.argv:
            args['level'] = 20
            func(**args)
        else:
            args['level'] = 40
            func(**args)

        if not '--no-daemon' in sys.argv:
            startstop(stdout=os.getcwd()+'/userbot-error.log',
                      stderr=os.getcwd()+'/userbot.log',
                      pidfile='/tmp/userbot.pid',
                      startmsg='UserBot started with PID: %s')
            os.chdir(PATH)

        if not os.path.exists('db/userbot'):
            import logging
            logging.error('missing database file!')
            return

        from sysb.commands import commands
        commands.load_modules()

        from irc.connection import load_connections as load
        load()
        commands.endless_process()

    elif sys.argv[1] == '--help':
        #os.chdir(PATH)
        with open('docs/man.rst') as man:
            for line in man.read().splitlines():
                print line

    elif sys.argv[1] == '--make-config':
        from sysb.make_config import make
        make()

    else:
        print "Forma de uso: userbot --(start|stop|restart|make-config|help)"
        print "Para mas información: userbot --help"

if __name__ == '__main__':
    main()